name: Auto Deploy to Test and Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches from the remote repository
        run: git fetch --all

      - name: Fetch latest changes from main to Prod Branch
        run: |
          git checkout prod
          git merge --allow-unrelated-histories origin/main
          git merge origin/main
          git add .
          git commit -m "added new line"
          git push origin prod
