name: Auto Deploy to Test and Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Test Branch
        run: |
          git checkout -b test
          git add .
          git commit -m "added new line"
          git push origin test

      - name: Push to Prod Branch
        run: |
          git checkout -b prod
          git add .
          git commit -m "added new line"
          git push origin prod
